version: '3.8'
services:
  db-stats:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db-main:
    image: postgres:13.7-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-server:
    build: ./main
    ports:
      - "8080:8080"
    depends_on:
      - db-main
      - stats-server
    environment:
      - SERVER_PORT=8080
      - STATS-SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-main:5432/main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: ./stat
    ports:
      - "9090:9090"
    depends_on:
      - db-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-stats:5432/stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SERVER-PORT=9090
