spring:
  datasource:
    username: root
    url: jdbc:postgresql://db-stats:5432/stat
    driverClassName: org.postgresql.Driver
    password: root
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 9090
...
---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    username: test
    url: jdbc:h2:mem:stat
    driverClassName: org.h2.Driver
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
