spring:
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/ewm
    driverClassName: org.postgresql.Driver
    password: root
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
stat-server:
  url: http://localhost:9090
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

...
---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    username: test
    url: jdbc:h2:mem:ewm
    driverClassName: org.h2.Driver
    password: test
